### ISSUE TITLE
Can't install from NPM

### ISSUE THREAD

**Issue by filipjohansson** [jleibund/emojs#1]
I get this error when I try to install Emojs via npm.
I can send you the full npm-debug.log if you want to.

```
> emojs@0.0.1 install /Applications/EmotivXavierResearch/node/filips-test/node_modules/emojs
> node-gyp rebuild

Warning: Ignoring not yet implemented key "ARCHS".
Warning: Ignoring not yet implemented key "ARCHS".
Warning: Ignoring not yet implemented key "ARCHS".
Warning: Ignoring not yet implemented key "ARCHS".
  CXX(target) Release/obj.target/emojs/NodeEPOCDriver.o
../NodeEPOCDriver.cc:12:10: fatal error: 'edk.h' file not found
#include "edk.h"
         ^
1 error generated.
make: *** [Release/obj.target/emojs/NodeEPOCDriver.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/EmotivXavierResearch/node/filips-test/node_modules/emojs
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "emojs"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! emojs@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the emojs@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the emojs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls emojs
npm ERR! There is likely additional logging output above.
```

**Comment by jleibund** [comment]
Can you verify that you have installed the SDK first (a prerequisite).  If so you should see edk.h in /usr/local/include

Or for that matter, the other files that you can see referenced in the binding.gyp file in this repo.

The error above says it can't find edk.h where it's usually installed which means either you don't have it installed (no SDK) or Emotiv has changed where this lives now in later versions (I wrote this several years ago)

**Comment by filipjohansson** [comment]
Thank you for your quick reply.

I do not have that file. When I downloaded the SDK I got a folder called `lib` in my applications folder (I am running OS X if that wasn't clear). In that folder I can find these files `libedk_ultils_mac.dylib`, `libedk.1.0.0.dylib`, `libedk.1.0.dylib` (alias), `libedk.1.dylib` (alias), `libedk.dylib` (alias) and `libiomp5.dylib`.

**Comment by jleibund** [comment]
Sorry for the long no-reply.  I'm not actively maintaining this right now so its possible that Emotiv changed things - files or where they are located.  Still, you should see if you can find this C header file and if necessary just change the Make file to suit.  It would probably be located in an "include" directory if your SDK has that.
